### ISSUE TITLE
isCrop and isCropSquare is not present in latest build .

### ISSUE THREAD

**Issue by kashifansari786** [isudev/Matisse#1]
isCrop and isCropSquare is not present in latest build but in example you show that this function is present in build ,kindly tell me how can i call this functions.

**Comment by isuudev** [comment]
dependencies {
    implementation project(':matisse')
}

Matisse.from(MainActivity.this)
        .choose(MimeType.ofImage(), true)
        .countable(true)
        .addFilter(new GifSizeFilter(320, 320, 5 * Filter.K * Filter.K))
        .gridExpectedSize(getResources().getDimensionPixelSize(R.dimen.grid_expected_size))
        .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
        .thumbnailScale(0.85f)
        .imageEngine(new GlideEngine())
        .maxSelectable(1)
        .isCrop(true)
        .isCropSquare(false)
        .forResult(REQUEST_CODE_CHOOSE);
